# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


set(CPACK_BUILD_SOURCE_DIRS "/home/aviannvidia/dronene/uhd/host;/home/aviannvidia/dronene/uhd/host/python")
set(CPACK_CMAKE_GENERATOR "Unix Makefiles")
set(CPACK_COMPONENTS_ALL "libraries;pythonapi;headers;utilities;examples;manual;doxygen;readme;images")
set(CPACK_COMPONENTS_ALL_SET_BY_USER "TRUE")
set(CPACK_COMPONENT_DOXYGEN_DESCRIPTION "API documentation (html)")
set(CPACK_COMPONENT_DOXYGEN_DISPLAY_NAME "Doxygen")
set(CPACK_COMPONENT_DOXYGEN_GROUP "Documentation")
set(CPACK_COMPONENT_EXAMPLES_DEPENDS "libraries")
set(CPACK_COMPONENT_EXAMPLES_DESCRIPTION "Example executables")
set(CPACK_COMPONENT_EXAMPLES_DISPLAY_NAME "Examples")
set(CPACK_COMPONENT_EXAMPLES_GROUP "Runtime")
set(CPACK_COMPONENT_HEADERS_DESCRIPTION "C++ development headers")
set(CPACK_COMPONENT_HEADERS_DISPLAY_NAME "C++ Headers")
set(CPACK_COMPONENT_HEADERS_GROUP "Development")
set(CPACK_COMPONENT_IMAGES_DESCRIPTION "FPGA and firmware images")
set(CPACK_COMPONENT_IMAGES_DISPLAY_NAME "Images")
set(CPACK_COMPONENT_LIBRARIES_DESCRIPTION "Dynamic link library")
set(CPACK_COMPONENT_LIBRARIES_DISPLAY_NAME "Libraries")
set(CPACK_COMPONENT_LIBRARIES_GROUP "Development")
set(CPACK_COMPONENT_MANUAL_DESCRIPTION "Manual/application notes (rst and html)")
set(CPACK_COMPONENT_MANUAL_DISPLAY_NAME "Manual")
set(CPACK_COMPONENT_MANUAL_GROUP "Documentation")
set(CPACK_COMPONENT_PYTHONAPI_DESCRIPTION "UHD Python API")
set(CPACK_COMPONENT_PYTHONAPI_DISPLAY_NAME "UHD Python API")
set(CPACK_COMPONENT_PYTHONAPI_GROUP "Development")
set(CPACK_COMPONENT_README_DESCRIPTION "Readme files (txt)")
set(CPACK_COMPONENT_README_DISPLAY_NAME "Readme")
set(CPACK_COMPONENT_README_GROUP "Documentation")
set(CPACK_COMPONENT_README_REQUIRED "TRUE")
set(CPACK_COMPONENT_TESTS_DEPENDS "libraries")
set(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
set(CPACK_COMPONENT_UTILITIES_DEPENDS "libraries")
set(CPACK_COMPONENT_UTILITIES_DESCRIPTION "Utility executables and python scripts")
set(CPACK_COMPONENT_UTILITIES_DISPLAY_NAME "Utilities")
set(CPACK_COMPONENT_UTILITIES_GROUP "Runtime")
set(CPACK_COMPONENT_WINLUSBSUPPORT_DESCRIPTION "Ettus USB driver installers")
set(CPACK_COMPONENT_WINUSBSUPPORT_DISPLAY_NAME "USB Drivers")
set(CPACK_COMPONENT_WINUSBSUPPORT_GROUP "Runtime")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_FILE "/usr/share/cmake-3.22/Templates/CPack.GenericDescription.txt")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_SUMMARY "UHD built using CMake")
set(CPACK_GENERATOR "TGZ")
set(CPACK_INSTALL_CMAKE_PROJECTS "/home/aviannvidia/dronene/uhd/host/python;UHD;ALL;/")
set(CPACK_INSTALL_PREFIX "/usr/local")
set(CPACK_MODULE_PATH "/home/aviannvidia/dronene/uhd/host/cmake/Modules")
set(CPACK_NSIS_DISPLAY_NAME "UHD 4.9.0.0-107-gea40e659")
set(CPACK_NSIS_EXTRA_INSTALL_COMMANDS "
    WriteRegStr HKLM \"SYSTEM\\CurrentControlSet\\Control\\Session Manager\\Environment\" \"UHD_PKG_PATH\" \"$INSTDIR\"
")
set(CPACK_NSIS_EXTRA_UNINSTALL_COMMANDS "
    DeleteRegValue HKLM \"SYSTEM\\CurrentControlSet\\Control\\Session Manager\\Environment\" \"UHD_PKG_PATH\"
")
set(CPACK_NSIS_INSTALLED_ICON_NAME "Uninstall.exe")
set(CPACK_NSIS_INSTALLER_ICON_CODE "")
set(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
set(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES")
set(CPACK_NSIS_MODIFY_PATH "ON")
set(CPACK_NSIS_MUI_ICON "/home/aviannvidia/dronene/uhd/host/cmake/Modules/ettus_256x256.ico")
set(CPACK_NSIS_MUI_UNIICON "/home/aviannvidia/dronene/uhd/host/cmake/Modules/ettus_256x256.ico")
set(CPACK_NSIS_PACKAGE_NAME "UHD 4.9.0.0-107-gea40e659")
set(CPACK_NSIS_UNINSTALL_NAME "Uninstall")
set(CPACK_OUTPUT_CONFIG_FILE "/home/aviannvidia/dronene/uhd/host/python/CPackConfig.cmake")
set(CPACK_PACKAGE_CONTACT "Ettus Research <uhd.maintainer@emerson.com>")
set(CPACK_PACKAGE_COPYRIGHT "Copyright © 2010-2025 Ettus Research, a National Instruments Company")
set(CPACK_PACKAGE_DEFAULT_LOCATION "/")
set(CPACK_PACKAGE_DESCRIPTION_FILE "/usr/share/cmake-3.22/Templates/CPack.GenericDescription.txt")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Ettus Research - USRP Hardware Driver")
set(CPACK_PACKAGE_FILE_NAME "UHD-4.9.0.0-107-gea40e659-Linux")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "UHD 4.9.0.0-107-gea40e659")
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "UHD 4.9.0.0-107-gea40e659")
set(CPACK_PACKAGE_NAME "UHD")
set(CPACK_PACKAGE_RELOCATABLE "true")
set(CPACK_PACKAGE_VENDOR "Ettus Research (NI, now part of Emerson)")
set(CPACK_PACKAGE_VERSION "4.9.0.0-107-gea40e659")
set(CPACK_PACKAGE_VERSION_MAJOR "0")
set(CPACK_PACKAGE_VERSION_MINOR "1")
set(CPACK_PACKAGE_VERSION_PATCH "1")
set(CPACK_RESOURCE_FILE_LICENSE "/home/aviannvidia/dronene/uhd/host/LICENSE")
set(CPACK_RESOURCE_FILE_README "/usr/share/cmake-3.22/Templates/CPack.GenericDescription.txt")
set(CPACK_RESOURCE_FILE_WELCOME "/home/aviannvidia/dronene/uhd/host/README.md")
set(CPACK_RPM_EXCLUDE_FROM_AUTO_FILELIST_ADDITION "/usr/share/man;/usr/share/man/man1;/usr/lib64/pkgconfig;/usr/lib64/cmake;/usr/lib64/python2.7;/usr/lib64/python2.7/site-packages")
set(CPACK_RPM_FILE_NAME ".rpm")
set(CPACK_RPM_PACKAGE_REQUIRES "boost-devel, python3-requests")
set(CPACK_RPM_POST_INSTALL_SCRIPT_FILE "/home/aviannvidia/dronene/uhd/host/python/redhat/post_install")
set(CPACK_RPM_POST_UNINSTALL_SCRIPT_FILE "/home/aviannvidia/dronene/uhd/host/python/redhat/post_uninstall")
set(CPACK_RPM_PRE_INSTALL_SCRIPT_FILE "/home/aviannvidia/dronene/uhd/host/python/redhat/pre_install")
set(CPACK_RPM_PRE_UNINSTALL_SCRIPT_FILE "/home/aviannvidia/dronene/uhd/host/python/redhat/pre_uninstall")
set(CPACK_RPM_SPEC_MORE_DEFINE "%global __python %{__python3}")
set(CPACK_SET_DESTDIR "OFF")
set(CPACK_SOURCE_GENERATOR "TBZ2;TGZ;TXZ;TZ")
set(CPACK_SOURCE_IGNORE_FILES "\\.git*;\\.swp$")
set(CPACK_SOURCE_OUTPUT_CONFIG_FILE "/home/aviannvidia/dronene/uhd/host/python/CPackSourceConfig.cmake")
set(CPACK_SOURCE_PACKAGE_FILE_NAME "uhd-4.9.0.0-107-gea40e659")
set(CPACK_SOURCE_RPM "OFF")
set(CPACK_SOURCE_TBZ2 "ON")
set(CPACK_SOURCE_TGZ "ON")
set(CPACK_SOURCE_TXZ "ON")
set(CPACK_SOURCE_TZ "ON")
set(CPACK_SOURCE_ZIP "OFF")
set(CPACK_SYSTEM_NAME "Linux")
set(CPACK_THREADS "1")
set(CPACK_TOPLEVEL_TAG "Linux")
set(CPACK_WIX_SIZEOF_VOID_P "8")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "/home/aviannvidia/dronene/uhd/host/python/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
